version: 2

updates:
  - package-ecosystem: "pub"
    directory: "/packages/flutter_rbac_services"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_rbac_services_data_interface"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_rbac_services_firebase"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_rbac_services_rest"
    schedule:
      interval: "weekly"
