name: flutter_rbac_service
description: A new Flutter package project.
version: 2.4.3
repository: https://github.com/Iconica-Development/flutter_rbac
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  uuid: ^4.3.3
  logger: ^2.5.0

  flutter_rbac_service_data_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^2.4.3

dev_dependencies:
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^7.0.0
