name: flutter_rbac_service_data_interface
description: A new Flutter package project.
version: 2.4.1
repository: https://github.com/Iconica-Development/flutter_rbac
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/

environment:
  sdk: ">=3.4.0 <4.0.0"

dev_dependencies:
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^7.0.0
