name: flutter_rbac_view
description: A new Flutter package project.
version: 2.2.2
publish_to: https://forgejo.internal.iconica.nl/api/packages/internal/pub/


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: any  
  flutter_rbac_service_data_interface:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^2.2.2
  flutter_rbac_service:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^2.2.2
  flutter_menu:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^0.0.3

  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_iconica_analysis:
    hosted: https://forgejo.internal.iconica.nl/api/packages/internal/pub/
    version: ^6.0.0

flutter:
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir/Avenir-Regular.ttf
        - asset: assets/fonts/Avenir/Avenir-Heavy.ttf
          weight: 700
        - asset: assets/fonts/Avenir/Avenir-Black.ttf
          weight: 900

